apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: yneh9zpi3-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:8aeabbea4b5fcb219e7486fcc9037cfd4148df1b@sha256:139247dea46ff73f430f838999223d5831ab87b066eacc32fd7a6752571c86d6
          name: container-image
